In [3]:
import pandas as pd
import csv
import numpy as np
from scipy.spatial.distance import squareform, pdist

In [4]:
pdist([[0,0,1,0,1,0,1,0,1,0],[1,0,0,1,0,1,0,1,0,0]], 'cosine')

array([1.])

In [5]:
pdist([[0,0,1,0,1,0,1,0,1,0],[1,0,0,1,0,1,0,1,0,0]], 'correlation')

array([1.66666667])

In [6]:
pdist([[0,0,1,0,1,0,1,0,1,0],[1,0,0,1,0,1,0,1,0,0]], 'hamming')

array([0.8])

In [7]:
pdist([[0,0,1,0,1,0,1,0,1,0],[1,0,0,1,0,1,0,1,0,0]], 'jaccard')

array([1.])

In [9]:
pdist([[0,0,1,0,1,0,1,0,1,0],[1,0,0,1,0,1,0,1,0,0]], 'russellrao')

array([1.])

In [10]:
pdist([[1,0,1,0,1,0,1,0,1,1],[1,0,0,1,0,1,0,1,0,1]], 'cosine')

array([0.63485163])

In [15]:
pdist([[0,0,1,0,0,1,0,0,1,0],[0,0,1,0,0,1,0,0,1,0]], 'cosine')

array([0.])

In [16]:
pdist([[0,0,1,0,0,1,0,0,1,1],[0,0,1,0,0,1,0,0,1,0]], 'cosine')

array([0.1339746])

In [19]:
pdist([[0,0,1,0,0,0,0,0,1,1],[0,0,1,0,0,0,0,0,1,0]], 'cosine')

array([0.18350342])

In [22]:
pdist([[0,0,0,0,0,0,0,0,1,1],[0,0,0,0,0,0,0,0,0,1]], 'cosine')

array([0.29289322])

In [22]:
pdist([[0,0,0,0,0,0,0,0,1,1],[0,0,0,0,0,0,0,0,0,1]], 'cosine')

array([0.29289322])

In [26]:
pdist([[0,0,0,0,0,0,0,0,1,1],[0,0,0,0,0,0,0,0,1,0]], 'cosine')

array([0.29289322])

In [25]:
pdist([[0,0,0,0,0,0,0,0,1,1],[0,0,0,0,0,0,0,1,1,1]], 'cosine')

array([0.18350342])

In [27]:
pdist([[0,0,0,0,0,0,0,0,1,1],[0,0,0,0,0,0,0,1,0,1]], 'cosine')

array([0.5])

In [28]:
pdist([[0,0,0,0,0,0,0,0,1,1],[0,0,0,0,0,0,0,1,1,0]], 'cosine')

array([0.5])

In [11]:
pdist([[1,0,1,0,1,0,1,0,1,1],[1,0,0,1,0,1,0,1,0,1]], 'correlation')

array([1.40824829])

In [12]:
pdist([[1,0,1,0,1,0,1,0,1,1],[1,0,0,1,0,1,0,1,0,1]], 'hamming')

array([0.7])

In [13]:
pdist([[1,0,1,0,1,0,1,0,1,1],[1,0,0,1,0,1,0,1,0,1]], 'jaccard')

array([0.77777778])

In [14]:
pdist([[1,0,1,0,1,0,1,0,1,1],[1,0,0,1,0,1,0,1,0,1]], 'russellrao')

array([0.8])